version: '3.7'
networks:
  db_ip:
    ipam:
      config:
        - subnet: 172.16.5.0/24

services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    ports:
      - "5030:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_PASSWORD=100"
    expose:
      - '5030'
    networks:
        db_ip:
            ipv4_address: 172.16.5.2
    volumes:
      - /Users/cefalo/Desktop/RND/python/sql/data/postgres:/var/lib/postgresql/data
