"""Books and user migrations

Revision ID: 128e1f4c6383
Revises: 6351e6931f48
Create Date: 2023-08-06 17:23:18.949960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128e1f4c6383'
down_revision: Union[str, None] = '6351e6931f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('writer', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'writer')
    # ### end Alembic commands ###
