"""Consolidate migrations

Revision ID: 17b9f35594b3
Revises: 51ce9a23f9a4
Create Date: 2023-08-06 17:38:36.988609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b9f35594b3'
down_revision: Union[str, None] = '51ce9a23f9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
