"""Books and user migrations

Revision ID: 2087ea8f5172
Revises: 128e1f4c6383
Create Date: 2023-08-06 17:27:00.691916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2087ea8f5172'
down_revision: Union[str, None] = '128e1f4c6383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('writer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='books_pkey')
    )
    # ### end Alembic commands ###
