"""Books and user migrations

Revision ID: 51ce9a23f9a4
Revises: a1e5b4f7997f
Create Date: 2023-08-06 17:30:14.203763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ce9a23f9a4'
down_revision: Union[str, None] = 'a1e5b4f7997f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
